#/*
# * Revision Control Information
# *
# * $Source: /var/cvs/ig/util/Makefile,v $
# * $Author: aderry $
# * $Revision: 1.1.1.1 $
# * $Date: 2005/10/07 11:31:57 $
# *
# */
# util -- miscellaneous utility routines
#---------------------------------------------------------------------------

CAD	= /projects/octtools/octtools/$(MACHINE)
SIS	= ..
LINTCREATEFLAG = -C

P	= util
PSRC	= cpu_time.c cpu_stats.c getopt.c safe_mem.c strsav.c texpand.c \
	  prtime.c pipefork.c saveimage.c pathsearch.c stub.c \
	  restart.c state.c tmpfile.c datalimit.c
POBJ	= $(PSRC:.c=.o)
PHDR	= util.h
MISC	= $(P).doc Makefile test-restart.c

TARGET	= test-restart
SRC	= test-restart.c
OBJ	= test-restart.o
HDR	=

LIBS	=
LINTLIBS=
INCLUDE	= -I$(SIS)/include -I$(CAD)/include

FLAGS	= -DBSD_SIS -DUNIX
CFLAGS	= $(INCLUDE)
LDFLAGS	= 
LINTFLAGS =  $(INCLUDE) ${LINTEXTRAS}

.c.o:
	$(CC) -c $(CFLAGS) $(FLAGS) $*.c
#---------------------------------------------------------------------------

$(TARGET): $(PHDR) $(OBJ) $(POBJ) $(LIBS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJ) $(POBJ) $(LIBS)

lint: $(PSRC) $(PHDR) $(SRC) $(HDR)
	lint $(LINTFLAGS) $(SRC) $(PSRC) $(LINTLIBS)

install: lib$(P).a llib-l$(P).ln

lib$(P).a: $(POBJ)
	ar cr lib$(P).a $(POBJ)
	ranlib lib$(P).a

unpack: lib$(P).a
	@for i in $(POBJ); do				\
	    ln -s $(SIS)/$(P)/$$i $(SIS)/unpack;	\
	done

llib-l$(P).ln: $(PSRC) $(PHDR)
	lint $(LINTFLAGS) ${LINTCREATEFLAG}$(P) -n $(PSRC)

clean:
	rm -f $(TARGET) *.a *.ln *.o \
	    [Tt]ags [Mm]ake.out lint malloc.out gmon.out __.SYMDEF

tags: _force
	@for i in $(PSRC) $(PHDR); do			\
	    cwd=`pwd`; ctags -a $$cwd/$$i;		\
	done;

strip_depend:
	sed '/^#--DO NOT CHANGE ANYTHING AFTER THIS LINE/,$$d' Makefile >mktemp
	mv mktemp Makefile

depend:
	sed '/^#--DO NOT CHANGE ANYTHING AFTER THIS LINE/,$$d' Makefile >mktemp
	echo '#--DO NOT CHANGE ANYTHING AFTER THIS LINE' >>mktemp
	$(CAD)/bin/cc-M $(CFLAGS) $(PSRC) | \
	    sed 's|$(CAD)|$$(CAD)|g' | \
	    grep -v '/usr/include' >>mktemp
	mv mktemp Makefile

#-------------------------- IBM 3090 support -----------------
IBMHOST	= beeblebrox
IBMDIST	= 
ibmdist: $(PSRC) $(PHDR)
	rdist -Richw $(PSRC) $(PHDR) $(IBMHOST):$(IBMDIST)
#-------------------------------------------------------------
_force:

